import '@/styles/GlobalStyles.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { Footer, Header } from '@/components'
import StyledComponentsRegistry from './lib/registry'

const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <html lang="en">
        <body className={poppins.variable}>
          <Header />
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
          <Footer />
        </body>
      </html>
    </>
  )
}
