import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import GlobalStyles from '@/styles/GlobalStyles'
import { Footer, Header } from '@/components'

const poppins = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-poppins',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <>
      <GlobalStyles />
      <html lang="en">
        <body className={poppins.variable}>
          <Header /> {children} <Footer />
        </body>
      </html>
    </>
  )
}
